before_install:
  - sudo apt-get -qq update
  - sudo apt-get install swig
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:resources/libGLPK

language: java
jdk:
  - oraclejdk8

notifications:
  email: false

